### ISSUE TITLE
Mass Assignment issues in db/seeds.rb

### ISSUE THREAD

**Issue by calebhearth** [tapangi/rgmanager#15]
`rake db:seeds` is failing because there are mass assignments happening in db/seeds.rb.

Possible solutions:
- Remove Mass Assignment protections (not recommended as these protect from some security holes)
- Switch to StrongParameters This will require a pretty big refactor in the controllers, but won't require any changes to the `db/seeds.rb` file. I think it is probably the best solution in the long term as StrongParameters will be standard in Rails 4, but it is not the easiest solution to this specific issue.
- Don't assign the values to the models in db/seed with hashes, rather one line per attribute.

``` ruby
# Causes mass assignment issues
User.new(email: 'banana@example.com', name: 'george')

# Doesn't
user = User.new
user.email = 'banana@example.com'
user.name = 'george'
```

**Comment by psteininger** [comment]
Caleb

I am positive that there can be small changes to the seeds.rb which fix the
issue.

When trying to fix an issue always look where the issue is - system or
input. In this case it's an issue with input

I will take a look in the morning.

Thanks

Piotr
