### ISSUE TITLE
Main page gives an error after removing jquery-ui-rails gem

### ISSUE THREAD

**Issue by karlhigley** [tapangi/rgmanager#3]
The commit that removes the jquery-ui-rails gem doesn't remove the lines from application.js and application.css that reference it.

(Commit 8c0f1c4a37ea521b30a5cb894604abf841cc374d)

**Comment by psteininger** [comment]
The commit was made in error

Will push some thing to fix it soon

**Comment by karlhigley** [comment]
Emily and I have a pull request to submit here momentarily.

**Comment by psteininger** [comment]
Sounds good. Emily can apply it :)
