### ISSUE TITLE
Update devise

### ISSUE THREAD

**Issue by jkeam** [tapangi/rgmanager#6]
Devise has recently been patched bc of a security hole.  We should upgrade.

http://blog.plataformatec.com.br/2013/01/security-announcement-devise-v2-2-3-v2-1-3-v2-0-5-and-v1-5-3-released/

**Comment by psteininger** [comment]
Go ahead :-)

**Comment by jkeam** [comment]
I probably should open another ticket but rails should be upgraded too.

http://weblog.rubyonrails.org/2013/1/28/Rails-3-0-20-and-2-3-16-have-been-released/

**Comment by jkeam** [comment]
Actually just double checked gemfile, we are ok with our rails version.

**Comment by karlhigley** [comment]
The application is running Rails 3.2.8, so the security update linked above doesn't apply.  However, the latest patch version of Rails 3.2 is Rails 3.2.11, and some of the versions between 3.2.8 and 3.2.11 are security patches.  Opening a separate issue.

**Comment by jkeam** [comment]
Awesome

**Comment by psteininger** [comment]
all gem updated
